version: '3'

services:
  redis:
    env_file:
      - .env
    image: bitnami/redis:latest # поддерживает env REDIS_PASSWORD
    healthcheck:
      test: redis-cli -a $REDIS_PASSWORD ping || exit 1
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 5s
    ports:
      - 6379:6379

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 5000:3000
    restart: always
  
  wiremock:
    image: wiremock/wiremock:latest
    volumes:
      - $PWD/wiremock/extensions:/var/wiremock/extensions
      - $PWD/wiremock/mappings:/home/wiremock/mappings
      - $PWD/wiremock/__files:/home/wiremock/__files
    command:
      - "--max-request-journal-entries=1000"
      - "--container-threads=120"
      - "--extensions=com.github.masonm.JwtMatcherExtension,com.github.masonm.JwtStubMappingTransformer"
      - "--enable-stub-cors"
    ports:
      - 8080:8080
